### ISSUE TITLE
Graphs Should be grabbable and moveable

### ISSUE THREAD

**Issue by El-Dringo-Brannde** [El-Dringo-Brannde/Senior-Capstone-VR#15]
@El-Dringo-Brannde commented on [Fri Jan 26 2018](https://github.com/El-Dringo-Brannde/Senior-Capstone-Server/issues/44)

Somewhere along the lines.. again in the simulator. The ability to grab and move an object has been lost, please restore

**Comment by bensocar** [comment]
Updated in latest Unity Collab push
