### ISSUE TITLE
Set colliders for VR House

### ISSUE THREAD

**Issue by El-Dringo-Brannde** [El-Dringo-Brannde/Senior-Capstone-VR#24]
@El-Dringo-Brannde commented on [Fri Jan 26 2018](https://github.com/El-Dringo-Brannde/Senior-Capstone-Server/issues/49)

Currently there are no colliders for the user on the demo plane that was created. 

The user should be contained within the walls to be sure they don't wander outside the house. Along with being able to walk up the stairs if they want.

**Comment by bensocar** [comment]
Colliders added
